export const ROUTE = {
    LOGIN: 'login',
    LOGOUT: 'logout',
    FORGOT_PASSWORD: 'forgot-password',
    SIGN_UP: 'sign-up',
    // TWO_FACTOR_AUTHENTICATION: 'two-factor-authentication',
    // POMASTER_ADMIN_BUYERS: 'pomasteradmin/buyers',
    // POMASTER_ADMIN_BUYERS_ADD: 'pomasteradmin/buyers/add',
    // POMASTER_ADMIN_BUYERS_EDIT: 'pomasteradmin/buyers/edit',

    // BUYER_DASHBOARD: 'buyer/dashboard',
    // BUYER_BALANCE_SHEET: 'buyer/balance_sheet',
    // BUYER_INVOICES: 'buyer/invoices',
    // BUYER_ORDERS: 'buyer/orders',
    // BUYER_APPROVALS: 'buyer/approvals',
    // BUYER_PROCUREMENTS: 'buyer/procurements',
    // BUYER_WAREHOUSE: 'buyer/warehouse',
    // BUYER_WAREHOUSE_ADD: 'buyer/warehouse/add',
    // BUYER_WAREHOUSE_EDIT: 'buyer/warehouse/edit',
    // BUYER_USERS: 'buyer/users',
    // BUYER_USERS_ADD: 'buyer/users/add',
    // BUYER_USERS_EDIT: 'buyer/users/edit',
    // BUYER_PRODUCTS: 'buyer/products',
    // BUYER_PRODUCTS_IMPORT: 'buyer/import/products',
    // BUYER_PRODUCTS_ADD: 'buyer/products/add',
    // BUYER_PRODUCTS_EDIT: 'buyer/products/edit',
    // BUYER_SUPPLIERS: 'buyer/suppliers',
    // BUYER_SUPPLIERS_ADD: 'buyer/suppliers/add',
    // BUYER_SUPPLIERS_EDIT: 'buyer/suppliers/edit',
    // BUYER_SETTINGS: 'buyer/settings',
    // BUYER_IMPORT_SUPPLIER_PRODUCTS: 'buyer/import/supplier/products',
    // BUYER_IMPORT_WAREHOUSE_PRODUCTS: 'buyer/import/warehouse/products',

    // SUPPLIER_DASHBOARD: 'supplier/dashboard',
    // SUPPLIER_CHOOSE_BUYER_ACCOUNT: 'supplier/choose_buyer_account',
    // SUPPLIER_PRODUCTS: 'supplier/products',
    // SUPPLIER_USERS: 'supplier/users',
    // SUPPLIER_SETTINGS: 'supplier/settings',
    // SUPPLIER_PURCHASE_ORDERS: 'supplier/purchase_orders',
    // SUPPLIER_PRODUCTS_TO_FULFILL: 'supplier/product_to_fulfill',
    // SUPPLIER_BALANCE_SHEET: 'supplier/balance_sheet',
    // SUPPLIER_INVOICES: 'supplier/invoices',
    // SUPPLIERS_USER_ADD: 'supplier/users/add',
    // SUPPLIERS_USER_EDIT: 'supplier/users/edit',
    TERMS_AND_CONDITION: 'terms-and-conditions',
    EXPIRED: 'expired',
    PAGE_NOT_FOUND: 'page-not-found',
    SUPPLIER_PRODUCTS_DETAILS:'supplier/products/details',
}
